#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later or MIT

from libkit import *

if len(argv) < 3:
	exit(128)

srctree = env_or_die('SRCTREE')
objtree = env_or_die('SRCTREE')

dotconfig_pth = argv[1]
reconfdep_pth = argv[2]

if not path.exists(reconfdep_pth):
	open(reconfdep_pth, 'x').close()

sample = open(f"{srctree}/scripts/reconfdep.def", 'r')
dotconfig = open(dotconfig_pth, 'r')
reconfdep = open(reconfdep_pth, 'r')

dotconf = { 'y': True }
confdep = { 'y': True }

exec(dotconfig.read(), {}, dotconf)
exec(reconfdep.read(), {}, confdep)

deps = sample.read().split('\n')
deps = [ dep for dep in deps if dep and dep[0] != '#' ]
update = 0

for dep in deps:
	if dep in dotconf:
		if dep in confdep and dotconf[dep] == confdep[dep]:
			continue

		confdep[dep] = dotconf[dep]
	elif dep in confdep:
		del confdep[dep]
	else:
		continue

	update = 1

if not update:
	exit(0)

del confdep['y']

reconfdep = open(reconfdep_pth, 'r+')

head = '# Generated by scripts/reconfdep.py\n'
head_len = len(head)

if reconfdep.tell() == 0:
	reconfdep.write(head)
else:
	reconfdep.seek(head_len)

for dep in confdep:
	val = dotconf[dep]
	t = type(val)

	if t is bool:
		val = 'y'
	elif t is str:
		val = f"\"{val}\""

	reconfdep.write(f"\n{dep}={val}\n")

reconfdep.truncate()
